language: rust
rust:
  - stable
  - beta
  - nightly
after_success:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo bench  --features "unstable";
    fi
matrix:
  allow_failures:
    - rust: nightly